# Generated by Django 5.1.2 on 2024-11-06 09:28

import FirstApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROCESS', 'In Process'), ('SENT', 'Sent'), ('COMPLETED', 'Completed')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[FirstApp.models.Product.price_validator]),
        ),
    ]
